version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.11
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "81:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  admin:
    build:
      context: .
      dockerfile: cmd/admin/Dockerfile
    environment:
      - ADMIN_ADDRESS=:8081
    ports:
      - "8081:8081"
    labels:
      - "traefik.http.routers.admin.rule=Host(`admin.docker.localhost`)"
